### ISSUE TITLE
'Web', 'Acting', 'Directing' links not working

### ISSUE THREAD

**Issue by dmp359** [jtmclucas13/new-portfolio#1]
Navigating to http://www.joshuamclucas.com/portfolio/ and the links don't work on the same page. Opening each link in a new tab does work.

**Comment by dmp359** [comment]
bump

**Comment by jtmclucas13** [comment]
@dmp359 - please see [this pull request](https://github.com/jtmclucas13/portfoilo/pull/1) under a different repo. This repo will be archived, as it is not the code for my portfolio site...lots of confusion 3 years ago when i first started redesigning/messing around with it.
